# Generated by Django 5.2.5 on 2025-08-25 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_in_date', models.DateField()),
                ('lease_duration_months', models.IntegerField(help_text='Duration of the lease in months.')),
                ('check_out_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Leased', 'Leased')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaseAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_signed_by_tenant', models.BooleanField(default=False)),
                ('is_signed_by_landlord', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landlord_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_leases', to=settings.AUTH_USER_MODEL)),
                ('tenant_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_leases', to=settings.AUTH_USER_MODEL)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lease_agreement', to='rental.rentalapplication')),
            ],
        ),
        migrations.CreateModel(
            name='RentalHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.FloatField(default=0)),
                ('furnishing_style', models.CharField(choices=[('Fully_Furnished', 'Fully Furnished'), ('Semi_Furnished', 'Semi Furnished'), ('None_Furnished', 'None Furnished')], max_length=20)),
                ('bedroom', models.CharField(choices=[('1_bedroom', '1 Bedroom'), ('2_bedroom', '2 Bedroom'), ('3_bedroom', '3 Bedroom'), ('4_bedroom', '4 Bedroom'), ('5_bedroom', '5 Bedroom'), ('bedsitter', 'Bedsitter'), ('other', 'Other')], max_length=20)),
                ('bathroom', models.CharField(choices=[('1_bathroom', '1 Bathroom'), ('2_bathroom', '2 Bathroom'), ('3_bathroom', '3 Bathroom'), ('4_bathroom', '4 Bathroom'), ('all_ensuite', 'All Ensuite'), ('other', 'Other')], max_length=20)),
                ('location', models.CharField(max_length=30)),
                ('rules', models.TextField()),
                ('amenities', models.TextField()),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_houses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='rental.rentalhouse'),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='house_directory_path')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rental.rentalhouse')),
            ],
        ),
    ]
