# Generated by Django 5.2.5 on 2025-08-27 08:03

import rental.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='images',
            field=models.ImageField(upload_to=rental.models.house_directory_path),
        ),
    ]
