# Generated by Django 5.2.5 on 2025-08-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_alter_images_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalapplication',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
