# Generated by Django 5.2.5 on 2025-08-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_rentalapplication_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalapplication',
            name='is_available',
        ),
        migrations.AddField(
            model_name='rentalhouse',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
