# Generated by Django 5.2.5 on 2025-08-28 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_remove_rentalapplication_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalapplication',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='rental.rentalhouse'),
        ),
    ]
