# Generated by Django 5.2.5 on 2025-08-30 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_alter_rentalapplication_house'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='images',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='leaseagreement',
            name='landlord_user',
        ),
        migrations.RemoveField(
            model_name='leaseagreement',
            name='tenant_user',
        ),
        migrations.RemoveField(
            model_name='rentalapplication',
            name='check_out_date',
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentalhouse',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
