# Generated by Django 5.2.5 on 2025-08-21 10:45

import owned_home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owned_home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='images',
        ),
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.ImageField(default='exit', upload_to=owned_home.models.house_directory_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownedhouse',
            name='name',
            field=models.CharField(default='exit', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ownedhouse',
            name='house_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
