# Generated by Django 5.2.5 on 2025-08-27 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owned_home', '0002_housepurchase_delete_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housepurchase',
            name='house',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='owned_home.ownedhouse'),
        ),
    ]
