# Generated by Django 5.2.5 on 2025-08-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owned_home', '0003_alter_housepurchase_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownedhouse',
            name='is_for_sale',
            field=models.BooleanField(default=True),
        ),
    ]
