# Generated by Django 5.2.5 on 2025-08-30 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owned_home', '0004_ownedhouse_is_for_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housepurchase',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_purchases', to='owned_home.ownedhouse'),
        ),
        migrations.AlterField(
            model_name='ownedhouse',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
