# Generated by Django 5.2.5 on 2025-08-16 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirbnbHouse',
            fields=[
                ('house_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('furnishing_style', models.CharField(choices=[('Fully_Furnished', 'Fully Furnished'), ('Semi_Furnished', 'Semi Furnished')], max_length=20)),
                ('bedroom', models.CharField(choices=[('1_bedroom', '1 Bedroom'), ('2_bedroom', '2 Bedroom'), ('3_bedroom', '3 Bedroom'), ('4_bedroom', '4 Bedroom'), ('5_bedroom', '5 Bedroom'), ('bedsitter', 'Bedsitter'), ('other', 'Other')], max_length=20)),
                ('bathroom', models.CharField(choices=[('1_bathroom', '1 Bathroom'), ('2_bathroom', '2 Bathroom'), ('3_bathroom', '3 Bathroom'), ('4_bathroom', '4 Bathroom'), ('all_ensuite', 'All Ensuite'), ('other', 'Other')], max_length=20)),
                ('location', models.CharField(max_length=30)),
                ('rules', models.TextField()),
                ('amenities', models.TextField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airbnb_houses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airbnb_bookings', to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='airbnb.airbnbhouse')),
            ],
        ),
        migrations.CreateModel(
            name='Checkdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateTimeField()),
                ('checkout', models.DateTimeField()),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_dates', to='airbnb.booking')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='airbnb.airbnbhouse')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='house_directory_path')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='airbnb.airbnbhouse')),
            ],
        ),
    ]
