# Generated by Django 5.2.5 on 2025-08-25 08:13

import airbnb.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirbnbHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('furnishing_style', models.CharField(choices=[('Fully_Furnished', 'Fully Furnished'), ('Semi_Furnished', 'Semi Furnished')], max_length=20)),
                ('bedroom', models.CharField(choices=[('1_bedroom', '1 Bedroom'), ('2_bedroom', '2 Bedroom'), ('3_bedroom', '3 Bedroom'), ('4_bedroom', '4 Bedroom'), ('5_bedroom', '5 Bedroom'), ('bedsitter', 'Bedsitter'), ('other', 'Other')], max_length=20)),
                ('bathroom', models.CharField(choices=[('1_bathroom', '1 Bathroom'), ('2_bathroom', '2 Bathroom'), ('3_bathroom', '3 Bathroom'), ('4_bathroom', '4 Bathroom'), ('all_ensuite', 'All Ensuite'), ('other', 'Other')], max_length=20)),
                ('location', models.CharField(max_length=30)),
                ('rules', models.TextField()),
                ('amenities', models.TextField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airbnb_houses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airbnb_bookings', to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='airbnb.airbnbhouse')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=airbnb.models.house_directory_path)),
                ('is_primary', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='airbnb.airbnbhouse')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
