# Generated by Django 5.2.5 on 2025-08-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airbnbhouse',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
