# Generated by Django 5.2.5 on 2025-08-21 09:50

import airbnb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=airbnb.models.house_directory_path),
        ),
    ]
