# Generated by Django 5.2.5 on 2025-08-19 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='images',
            new_name='image',
        ),
    ]
