# Generated by Django 5.2.5 on 2025-08-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0002_alter_images_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='check_out_date',
        ),
        migrations.AlterField(
            model_name='checkdates',
            name='checkin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='checkdates',
            name='checkout',
            field=models.DateField(),
        ),
    ]
