# Generated by Django 5.2.5 on 2025-08-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0003_remove_booking_check_in_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['position']},
        ),
        migrations.RemoveField(
            model_name='airbnbhouse',
            name='house_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='airbnbhouse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='booking',
            name='checkin',
            field=models.DateField(default='exit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='checkout',
            field=models.DateField(default='exit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='images',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='images',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Checkdates',
        ),
    ]
